language: node_js
node_js:
  - "6.11.1"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  # - yarn test:check-coverage
  - npm run lint
  - npm run test
after_script:
  # - yarn report-coverage
