version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "login:1:1,logout:1:1,play_episode:1:1,pause_episode:1:1,like_episode:1:1,completed_episode:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
